# Generated by Django 4.2 on 2023-05-06 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('legal_name_company', models.CharField(max_length=100, verbose_name='Kompaniyaninhg yuridik nomi')),
                ('description', models.TextField(max_length=500, verbose_name='Tavsif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Vakansiya nomi')),
                ('salary_type', models.CharField(choices=[('1', 'Aniq'), ('0', 'Noaniq')], max_length=20, verbose_name='Maosh turi')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boshlang`ich maosh')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oxirgi maosh')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aniq maosh')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Bo`sh ish o`rni',
                'verbose_name_plural': 'Bo`sh ish o`rinlari',
            },
        ),
    ]
